import type { AnalysisResponse } from "@/lib/types";

export const sampleAnalysis: AnalysisResponse = {
  schemaVersion: 1,
  songId: "sample-track",
  songName: "Sample Groove",
  audioFileName: "sample-track.mp3",
  analysisVersion: "2026-03-12",
  globalBpm: 116.0,
  offsetSec: 0.21,
  songLengthSec: 24.8,
  candidateEvents: [
    {
      id: "evt-0001",
      timeSec: 0.21,
      beatIndex: 1,
      barIndex: 1,
      beatInBar: 1,
      slotInBeat: 0,
      gridDivision: 1,
      timingRole: "downbeat",
      confidence: 0.91,
      strength: 0.94,
      kind: "strong",
      reason: "Bar-start pulse matched a local onset. Strong local energy.",
    },
    {
      id: "evt-0003",
      timeSec: 0.727,
      beatIndex: 1,
      barIndex: 1,
      beatInBar: 1,
      slotInBeat: 2,
      gridDivision: 2,
      timingRole: "offbeat",
      confidence: 0.68,
      strength: 0.71,
      kind: "steady",
      reason: "Eighth-note offbeat matched a local onset. Stable local energy.",
    },
    {
      id: "evt-0005",
      timeSec: 0.986,
      beatIndex: 2,
      barIndex: 1,
      beatInBar: 2,
      slotInBeat: 1,
      gridDivision: 4,
      timingRole: "subdivision",
      confidence: 0.79,
      strength: 0.83,
      kind: "strong",
      reason: "Sixteenth-note subdivision matched a local onset. Strong local energy.",
    },
    {
      id: "evt-0008",
      timeSec: 1.503,
      beatIndex: 3,
      barIndex: 1,
      beatInBar: 3,
      slotInBeat: 0,
      gridDivision: 1,
      timingRole: "beat",
      confidence: 0.52,
      strength: 0.58,
      kind: "light",
      reason: "Quarter-note pulse matched a local onset. Lighter local energy.",
    },
    {
      id: "evt-0010",
      timeSec: 2.02,
      beatIndex: 4,
      barIndex: 1,
      beatInBar: 4,
      slotInBeat: 2,
      gridDivision: 2,
      timingRole: "offbeat",
      confidence: 0.61,
      strength: 0.63,
      kind: "steady",
      reason: "Eighth-note offbeat matched a local onset. Stable local energy.",
    },
  ],
};
