import type { AnalysisResponse } from "@/lib/types";

const reactiveEvents = [
  {
    id: "rct-evt-00001",
    timeSec: 0.214,
    beatIndex: 1,
    barIndex: 1,
    beatInBar: 1,
    slotInBeat: 0,
    gridDivision: 1 as const,
    timingRole: "pulse" as const,
    confidence: 0.86,
    strength: 0.9,
    kind: "strong" as const,
    sceneFamily: "reactive" as const,
    sceneType: "prep_1_attack" as const,
    sceneGroupId: "rct-prep-1-001",
    cueTimesSec: [0.0],
    reason: "Reactive grammar candidate (1 prep + attack). One prep beat leads into the attack.",
  },
  {
    id: "rct-evt-00002",
    timeSec: 1.387,
    beatIndex: 3,
    barIndex: 1,
    beatInBar: 3,
    slotInBeat: 0,
    gridDivision: 0 as const,
    timingRole: "freeAccent" as const,
    confidence: 0.74,
    strength: 0.79,
    kind: "steady" as const,
    sceneFamily: "reactive" as const,
    sceneType: "prep_2_attack" as const,
    sceneGroupId: "rct-prep-2-001",
    cueTimesSec: [0.98, 1.18],
    reason: "Reactive grammar candidate (2 prep + attack). Two prep beats build into the attack.",
  },
  {
    id: "rct-evt-00003",
    timeSec: 2.281,
    beatIndex: 5,
    barIndex: 2,
    beatInBar: 1,
    slotInBeat: 0,
    gridDivision: 1 as const,
    timingRole: "pulse" as const,
    confidence: 0.82,
    strength: 0.85,
    kind: "strong" as const,
    sceneFamily: "reactive" as const,
    sceneType: "prep_3_attack" as const,
    sceneGroupId: "rct-prep-3-001",
    cueTimesSec: [1.468, 1.741, 2.02],
    reason: "Reactive grammar candidate (3 prep + attack). Three prep beats build a long wind-up before the attack.",
  },
  {
    id: "rct-evt-00004",
    timeSec: 2.694,
    beatIndex: 6,
    barIndex: 2,
    beatInBar: 2,
    slotInBeat: 0,
    gridDivision: 1 as const,
    timingRole: "pulse" as const,
    confidence: 0.8,
    strength: 0.83,
    kind: "steady" as const,
    sceneFamily: "reactive" as const,
    sceneType: "prep_1_attack" as const,
    sceneGroupId: "rct-prep-1-002",
    cueTimesSec: [2.281],
    reason: "Reactive grammar candidate (1 prep + attack). One prep beat leads into the attack.",
  },
];

const patternCueEvents1Bar = [
  {
    id: "ptn-cue-001-01",
    timeSec: 2.281,
    beatIndex: 5,
    barIndex: 2,
    beatInBar: 1,
    slotInBeat: 0,
    gridDivision: 1 as const,
    timingRole: "pulse" as const,
    confidence: 0.8,
    strength: 0.84,
    kind: "strong" as const,
    sceneFamily: "pattern" as const,
    sceneType: "combo_pattern_1bar" as const,
    sceneGroupId: "ptn-grp-001",
    cueTimesSec: [],
    reason: "1-bar combo-pattern cue motif. Listen to bars 2-2 before the response begins.",
  },
  {
    id: "ptn-cue-001-02",
    timeSec: 2.798,
    beatIndex: 6,
    barIndex: 2,
    beatInBar: 2,
    slotInBeat: 1,
    gridDivision: 2 as const,
    timingRole: "offbeat" as const,
    confidence: 0.75,
    strength: 0.79,
    kind: "steady" as const,
    sceneFamily: "pattern" as const,
    sceneType: "combo_pattern_1bar" as const,
    sceneGroupId: "ptn-grp-001",
    cueTimesSec: [],
    reason: "1-bar combo-pattern cue motif. Listen to bars 2-2 before the response begins.",
  },
];

const patternCueEvents2Bar = [
  {
    id: "ptn-cue-002-01",
    timeSec: 4.349,
    beatIndex: 9,
    barIndex: 3,
    beatInBar: 1,
    slotInBeat: 0,
    gridDivision: 1 as const,
    timingRole: "pulse" as const,
    confidence: 0.78,
    strength: 0.82,
    kind: "strong" as const,
    sceneFamily: "pattern" as const,
    sceneType: "combo_pattern_2bar" as const,
    sceneGroupId: "ptn-grp-002",
    cueTimesSec: [],
    reason: "2-bar combo-pattern cue motif. Listen to bars 3-4 before the response begins.",
  },
  {
    id: "ptn-cue-002-02",
    timeSec: 5.125,
    beatIndex: 10,
    barIndex: 3,
    beatInBar: 2,
    slotInBeat: 3,
    gridDivision: 4 as const,
    timingRole: "subdivision" as const,
    confidence: 0.7,
    strength: 0.74,
    kind: "steady" as const,
    sceneFamily: "pattern" as const,
    sceneType: "combo_pattern_2bar" as const,
    sceneGroupId: "ptn-grp-002",
    cueTimesSec: [],
    reason: "2-bar combo-pattern cue motif. Listen to bars 3-4 before the response begins.",
  },
];

const patternResponse1Bar = [
  {
    id: "ptn-evt-00001",
    timeSec: 4.349,
    beatIndex: 9,
    barIndex: 3,
    beatInBar: 1,
    slotInBeat: 0,
    gridDivision: 1 as const,
    timingRole: "pulse" as const,
    confidence: 0.79,
    strength: 0.82,
    kind: "strong" as const,
    sceneFamily: "pattern" as const,
    sceneType: "combo_pattern_1bar" as const,
    sceneGroupId: "ptn-grp-001",
    cueTimesSec: patternCueEvents1Bar.map((event) => event.timeSec),
    reason: "1-bar combo-pattern response candidate. Copy the motif shown in bars 2-2. The previous bars repeat with a clearly readable motif.",
  },
  {
    id: "ptn-evt-00002",
    timeSec: 4.866,
    beatIndex: 10,
    barIndex: 3,
    beatInBar: 2,
    slotInBeat: 1,
    gridDivision: 2 as const,
    timingRole: "offbeat" as const,
    confidence: 0.72,
    strength: 0.77,
    kind: "steady" as const,
    sceneFamily: "pattern" as const,
    sceneType: "combo_pattern_1bar" as const,
    sceneGroupId: "ptn-grp-001",
    cueTimesSec: patternCueEvents1Bar.map((event) => event.timeSec),
    reason: "1-bar combo-pattern response candidate. Copy the motif shown in bars 2-2. The previous bars repeat with a clearly readable motif.",
  },
];

const patternResponse2Bar = [
  {
    id: "ptn-evt-00003",
    timeSec: 7.125,
    beatIndex: 15,
    barIndex: 4,
    beatInBar: 3,
    slotInBeat: 1,
    gridDivision: 3 as const,
    timingRole: "triplet" as const,
    confidence: 0.7,
    strength: 0.74,
    kind: "steady" as const,
    sceneFamily: "pattern" as const,
    sceneType: "combo_pattern_2bar" as const,
    sceneGroupId: "ptn-grp-002",
    cueTimesSec: patternCueEvents2Bar.map((event) => event.timeSec),
    reason: "2-bar combo-pattern response candidate. Copy the motif shown in bars 3-4. The previous bars suggest a followable motif.",
  },
  {
    id: "ptn-evt-00004",
    timeSec: 7.52,
    beatIndex: 16,
    barIndex: 4,
    beatInBar: 4,
    slotInBeat: 0,
    gridDivision: 1 as const,
    timingRole: "pulse" as const,
    confidence: 0.75,
    strength: 0.8,
    kind: "strong" as const,
    sceneFamily: "pattern" as const,
    sceneType: "combo_pattern_2bar" as const,
    sceneGroupId: "ptn-grp-002",
    cueTimesSec: patternCueEvents2Bar.map((event) => event.timeSec),
    reason: "2-bar combo-pattern response candidate. Copy the motif shown in bars 3-4. The previous bars suggest a followable motif.",
  },
];

const patternSegments = [
  {
    id: "ptn-seg-001",
    bars: 1 as const,
    sceneType: "combo_pattern_1bar" as const,
    cueStartBar: 2,
    cueEndBar: 2,
    responseStartBar: 3,
    responseEndBar: 3,
    cueStartSec: 2.281,
    cueEndSec: 2.798,
    responseStartSec: 4.349,
    responseEndSec: 4.866,
    score: 0.81,
    similarity: 0.78,
    cueEvents: patternCueEvents1Bar,
    responseEventIds: patternResponse1Bar.map((event) => event.id),
  },
  {
    id: "ptn-seg-002",
    bars: 2 as const,
    sceneType: "combo_pattern_2bar" as const,
    cueStartBar: 3,
    cueEndBar: 4,
    responseStartBar: 5,
    responseEndBar: 6,
    cueStartSec: 4.349,
    cueEndSec: 5.125,
    responseStartSec: 7.125,
    responseEndSec: 7.52,
    score: 0.76,
    similarity: 0.67,
    cueEvents: patternCueEvents2Bar,
    responseEventIds: patternResponse2Bar.map((event) => event.id),
  },
];

const patternEvents = [...patternResponse1Bar, ...patternResponse2Bar];

const hybridEvents = [
  ...patternEvents.map((event, index) => ({
    ...event,
    id: `hyb-ptn-${String(index + 1).padStart(5, "0")}`,
    sceneGroupId: event.sceneGroupId.replace("ptn", "hyb-ptn"),
    reason: `Hybrid candidate inside a pattern response segment. ${event.reason}`,
  })),
  ...reactiveEvents.map((event, index) => ({
    ...event,
    id: `hyb-rct-${String(index + 1).padStart(5, "0")}`,
    sceneGroupId: event.sceneGroupId.replace("rct", "hyb-rct"),
    reason: `Hybrid candidate outside reserved pattern bars. ${event.reason}`,
  })),
];

const hybridPatternSegments = patternSegments.map((segment) => ({
  ...segment,
  id: segment.id.replace("ptn", "hyb-ptn"),
  cueEvents: segment.cueEvents.map((event) => ({
    ...event,
    id: event.id.replace("ptn", "hyb-ptn"),
    sceneGroupId: event.sceneGroupId.replace("ptn", "hyb-ptn"),
  })),
  responseEventIds: hybridEvents
    .filter((event) => event.sceneType === segment.sceneType && event.id.startsWith("hyb-ptn"))
    .map((event) => event.id),
}));

export const sampleAnalysis: AnalysisResponse = {
  schemaVersion: 1,
  songId: "sample-track",
  songName: "Sample Groove",
  audioFileName: "sample-track.mp3",
  analysisVersion: "2026-03-27",
  globalBpm: 116,
  offsetSec: 0.214,
  songLengthSec: 24.8,
  defaultCandidateStrategy: "hybrid",
  candidateEvents: hybridEvents,
  candidateVariants: [
    {
      strategy: "reactive",
      label: "반응형",
      description: "헤비 어택과 퀵 어택처럼 즉시 반응하는 입력 후보만 모아 둔 보기입니다.",
      candidateEvents: reactiveEvents,
      patternSegments: [],
    },
    {
      strategy: "pattern",
      label: "패턴형",
      description: "1마디와 2마디 콤보 패턴처럼 먼저 들은 뒤 따라치는 후보만 모아 둔 보기입니다.",
      candidateEvents: patternEvents,
      patternSegments,
    },
    {
      strategy: "hybrid",
      label: "반응형 + 패턴형",
      description: "패턴 구간은 유지하고, 나머지 공간은 반응형 입력으로 채운 혼합 보기입니다.",
      candidateEvents: hybridEvents,
      patternSegments: hybridPatternSegments,
    },
  ],
};
