import type { AnalysisResponse } from "@/lib/types";

const globalEvents = [
  {
    id: "gbl-evt-00001",
    timeSec: 0.21,
    beatIndex: 1,
    barIndex: 1,
    beatInBar: 1,
    slotInBeat: 0,
    gridDivision: 1 as const,
    timingRole: "pulse" as const,
    confidence: 0.91,
    strength: 0.94,
    kind: "strong" as const,
    reason: "Quarter-note pulse at a bar start matched a local onset. Strong local energy.",
  },
  {
    id: "gbl-evt-00002",
    timeSec: 0.727,
    beatIndex: 1,
    barIndex: 1,
    beatInBar: 1,
    slotInBeat: 1,
    gridDivision: 2 as const,
    timingRole: "offbeat" as const,
    confidence: 0.68,
    strength: 0.71,
    kind: "steady" as const,
    reason: "Eighth-note offbeat matched a local onset. Stable local energy.",
  },
  {
    id: "gbl-evt-00003",
    timeSec: 0.986,
    beatIndex: 2,
    barIndex: 1,
    beatInBar: 2,
    slotInBeat: 1,
    gridDivision: 4 as const,
    timingRole: "subdivision" as const,
    confidence: 0.79,
    strength: 0.83,
    kind: "strong" as const,
    reason: "Sixteenth-note subdivision matched a local onset. Strong local energy.",
  },
];

const sectionEvents = [
  ...globalEvents,
  {
    id: "s4b-evt-00004",
    timeSec: 1.116,
    beatIndex: 2,
    barIndex: 1,
    beatInBar: 2,
    slotInBeat: 3,
    gridDivision: 8 as const,
    timingRole: "thirtySecond" as const,
    confidence: 0.58,
    strength: 0.61,
    kind: "light" as const,
    reason: "Thirty-second subdivision matched a local onset. Lighter local energy.",
  },
  {
    id: "s4b-evt-00005",
    timeSec: 1.245,
    beatIndex: 2,
    barIndex: 1,
    beatInBar: 2,
    slotInBeat: 1,
    gridDivision: 3 as const,
    timingRole: "triplet" as const,
    confidence: 0.67,
    strength: 0.7,
    kind: "steady" as const,
    reason: "Triplet or shuffle subdivision matched a local onset. Stable local energy.",
  },
  {
    id: "s4b-evt-00006",
    timeSec: 1.382,
    beatIndex: 3,
    barIndex: 1,
    beatInBar: 3,
    slotInBeat: 0,
    gridDivision: 0 as const,
    timingRole: "freeAccent" as const,
    confidence: 0.73,
    strength: 0.77,
    kind: "steady" as const,
    reason: "Strong onset landed outside the current beat grid. Stable local energy.",
  },
];

export const sampleAnalysis: AnalysisResponse = {
  schemaVersion: 1,
  songId: "sample-track",
  songName: "Sample Groove",
  audioFileName: "sample-track.mp3",
  analysisVersion: "2026-03-13",
  globalBpm: 116.0,
  offsetSec: 0.21,
  songLengthSec: 24.8,
  defaultCandidateStrategy: "global",
  candidateEvents: globalEvents,
  candidateVariants: [
    {
      strategy: "global",
      label: "전곡 기준",
      description: "곡 전체 onset 에너지를 한 기준으로 보고 후보를 추출합니다.",
      candidateEvents: globalEvents,
    },
    {
      strategy: "section4bar",
      label: "4마디 기준",
      description: "4마디 단위로 onset 세기를 다시 평가해 조용한 구간의 상대 강세를 더 반영합니다.",
      candidateEvents: sectionEvents,
    },
  ],
};
